export default {
    en: {
        AFGHANISTAN: 'Afghanistan',
        ALBANIA: 'Albania',
        ALGERIA: 'Algeria',
        AMERICAN_SAMOA: 'American Samoa',
        ANDORRA: 'Andorra',
        ANGOLA: 'Angola',
        ANGUILLA: 'Anguilla',
        ANTARCTICA: 'Antarctica',
        ANTIGUA_AND_BARBUDA: 'Antigua and Barbuda',
        ARGENTINA: 'Argentina',
        ARMENIA: 'Armenia',
        ARUBA: 'Aruba',
        AUSTRALIA: 'Australia',
        AUSTRIA: 'Austria',
        AZERBAIJAN: 'Azerbaijan',
        BAHRAIN: 'Bahrain',
        BANGLADESH: 'Bangladesh',
        BARBADOS: 'Barbados',
        BELARUS: 'Belarus',
        BELGIUM: 'Belgium',
        BELIZE: 'Belize',
        BENIN: 'Benin',
        BERMUDA: 'Bermuda',
        BHUTAN: 'Bhutan',
        BOLIVIA: 'Bolivia',
        BOSNIA_AND_HERZEGOVINA: 'Bosnia and Herzegovina',
        BOTSWANA: 'Botswana',
        BOUVET_ISLAND: 'Bouvet Island',
        BRAZIL: 'Brazil',
        BRITISH_INDIAN_OCEAN_TERRITORY: 'British Indian Ocean Territory',
        BRITISH_VIRGIN_ISLANDS: 'British Virgin Islands',
        BRUNEI: 'Brunei',
        BULGARIA: 'Bulgaria',
        BURKINA_FASO: 'Burkina Faso',
        BURUNDI: 'Burundi',
        COTE_D_IVOIRE: 'Côte d\'Ivoire',
        CAMBODIA: 'Cambodia',
        CAMEROON: 'Cameroon',
        CANADA: 'Canada',
        CAPE_VERDE: 'Cape Verde',
        CAYMAN_ISLANDS: 'Cayman Islands',
        CENTRAL_AFRICAN_REPUBLIC: 'Central African Republic',
        CHAD: 'Chad',
        CHILE: 'Chile',
        CHINA: 'China',
        CHRISTMAS_ISLAND: 'Christmas Island',
        COCOS_KEELING_ISLANDS: 'Cocos (Keeling) Islands',
        COLOMBIA: 'Colombia',
        COMOROS: 'Comoros',
        CONGO: 'Congo',
        COOK_ISLANDS: 'Cook Islands',
        COSTA_RICA: 'Costa Rica',
        CROATIA: 'Croatia',
        CUBA: 'Cuba',
        CYPRUS: 'Cyprus',
        CZECH_REPUBLIC: 'Czech Republic',
        DEMOCRATIC_REPUBLIC_OF_THE_CONGO: 'Democratic Republic of the Congo',
        DENMARK: 'Denmark',
        DJIBOUTI: 'Djibouti',
        DOMINICA: 'Dominica',
        DOMINICAN_REPUBLIC: 'Dominican Republic',
        EAST_TIMOR: 'East Timor',
        ECUADOR: 'Ecuador',
        EGYPT: 'Egypt',
        EL_SALVADOR: 'El Salvador',
        EQUATORIAL_GUINEA: 'Equatorial Guinea',
        ERITREA: 'Eritrea',
        ESTONIA: 'Estonia',
        ETHIOPIA: 'Ethiopia',
        FAEROE_ISLANDS: 'Faeroe Islands',
        FALKLAND_ISLANDS: 'Falkland Islands',
        FIJI: 'Fiji',
        FINLAND: 'Finland',
        FORMER_YUGOSLAV_REPUBLIC_OF_MACEDONIA: 'Former Yugoslav Republic of Macedonia',
        FRANCE: 'France',
        FRENCH_GUIANA: 'French Guiana',
        FRENCH_POLYNESIA: 'French Polynesia',
        FRENCH_SOUTHERN_TERRITORIES: 'French Southern Territories',
        GABON: 'Gabon',
        GEORGIA: 'Georgia',
        GERMANY: 'Germany',
        GHANA: 'Ghana',
        GIBRALTAR: 'Gibraltar',
        GREECE: 'Greece',
        GREENLAND: 'Greenland',
        GRENADA: 'Grenada',
        GUADELOUPE: 'Guadeloupe',
        GUAM: 'Guam',
        GUATEMALA: 'Guatemala',
        GUINEA: 'Guinea',
        GUINEA_BISSAU: 'Guinea-Bissau',
        GUYANA: 'Guyana',
        HAITI: 'Haiti',
        HEARD_ISLAND_AND_MCDONALD_ISLANDS: 'Heard Island and McDonald Islands',
        HONDURAS: 'Honduras',
        HONG_KONG: 'Hong Kong',
        HUNGARY: 'Hungary',
        ICELAND: 'Iceland',
        INDIA: 'India',
        INDONESIA: 'Indonesia',
        IRAN: 'Iran',
        IRAQ: 'Iraq',
        IRELAND: 'Ireland',
        ISRAEL: 'Israel',
        ITALY: 'Italy',
        JAMAICA: 'Jamaica',
        JAPAN: 'Japan',
        JORDAN: 'Jordan',
        KAZAKHSTAN: 'Kazakhstan',
        KENYA: 'Kenya',
        KIRIBATI: 'Kiribati',
        KUWAIT: 'Kuwait',
        KYRGYZSTAN: 'Kyrgyzstan',
        LAOS: 'Laos',
        LATVIA: 'Latvia',
        LEBANON: 'Lebanon',
        LESOTHO: 'Lesotho',
        LIBERIA: 'Liberia',
        LIBYA: 'Libya',
        LIECHTENSTEIN: 'Liechtenstein',
        LITHUANIA: 'Lithuania',
        LUXEMBOURG: 'Luxembourg',
        MACAU: 'Macau',
        MADAGASCAR: 'Madagascar',
        MALAWI: 'Malawi',
        MALAYSIA: 'Malaysia',
        MALDIVES: 'Maldives',
        MALI: 'Mali',
        MALTA: 'Malta',
        MARSHALL_ISLANDS: 'Marshall Islands',
        MARTINIQUE: 'Martinique',
        MAURITANIA: 'Mauritania',
        MAURITIUS: 'Mauritius',
        MAYOTTE: 'Mayotte',
        MEXICO: 'Mexico',
        MICRONESIA: 'Micronesia',
        MOLDOVA: 'Moldova',
        MONACO: 'Monaco',
        MONGOLIA: 'Mongolia',
        MONTSERRAT: 'Montserrat',
        MOROCCO: 'Morocco',
        MOZAMBIQUE: 'Mozambique',
        MYANMAR: 'Myanmar',
        NAMIBIA: 'Namibia',
        NAURU: 'Nauru',
        NEPAL: 'Nepal',
        NETHERLANDS: 'Netherlands',
        NETHERLANDS_ANTILLES: 'Netherlands Antilles',
        NEW_CALEDONIA: 'New Caledonia',
        NEW_ZEALAND: 'New Zealand',
        NICARAGUA: 'Nicaragua',
        NIGER: 'Niger',
        NIGERIA: 'Nigeria',
        NIUE: 'Niue',
        NORFOLK_ISLAND: 'Norfolk Island',
        NORTH_KOREA: 'North Korea',
        NORTHERN_MARIANAS: 'Northern Marianas',
        NORWAY: 'Norway',
        OMAN: 'Oman',
        PAKISTAN: 'Pakistan',
        PALAU: 'Palau',
        PANAMA: 'Panama',
        PAPUA_NEW_GUINEA: 'Papua New Guinea',
        PARAGUAY: 'Paraguay',
        PERU: 'Peru',
        PHILIPPINES: 'Philippines',
        PITCAIRN_ISLANDS: 'Pitcairn Islands',
        POLAND: 'Poland',
        PORTUGAL: 'Portugal',
        PUERTO_RICO: 'Puerto Rico',
        QATAR: 'Qatar',
        REUNION: 'Réunion',
        ROMANIA: 'Romania',
        RUSSIA: 'Russia',
        RWANDA: 'Rwanda',
        SAO_TOME_AND_PRÍNCIPE: 'São Tomé and Príncipe',
        SAINT_HELENA: 'Saint Helena',
        SAINT_KITTS_AND_NEVIS: 'Saint Kitts and Nevis',
        SAINT_LUCIA: 'Saint Lucia',
        SAINT_PIERRE_AND_MIQUELON: 'Saint Pierre and Miquelon',
        SAINT_VINCENT_AND_THE_GRENADINES: 'Saint Vincent and the Grenadines',
        SAMOA: 'Samoa',
        SAN_MARINO: 'San Marino',
        SAUDI_ARABIA: 'Saudi Arabia',
        SENEGAL: 'Senegal',
        SEYCHELLES: 'Seychelles',
        SIERRA_LEONE: 'Sierra Leone',
        SINGAPORE: 'Singapore',
        SLOVAKIA: 'Slovakia',
        SLOVENIA: 'Slovenia',
        SOLOMON_ISLANDS: 'Solomon Islands',
        SOMALIA: 'Somalia',
        SOUTH_AFRICA: 'South Africa',
        SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS: 'South Georgia and the South Sandwich Islands',
        SOUTH_KOREA: 'South Korea',
        SPAIN: 'Spain',
        SRI_LANKA: 'Sri Lanka',
        SUDAN: 'Sudan',
        SURINAME: 'Suriname',
        SVALBARD_AND_JAN_MAYEN: 'Svalbard and Jan Mayen',
        SWAZILAND: 'Swaziland',
        SWEDEN: 'Sweden',
        SWITZERLAND: 'Switzerland',
        SYRIA: 'Syria',
        TAIWAN: 'Taiwan',
        TAJIKISTAN: 'Tajikistan',
        TANZANIA: 'Tanzania',
        THAILAND: 'Thailand',
        THE_BAHAMAS: 'The Bahamas',
        THE_GAMBIA: 'The Gambia',
        TOGO: 'Togo',
        TOKELAU: 'Tokelau',
        TONGA: 'Tonga',
        TRINIDAD_AND_TOBAGO: 'Trinidad and Tobago',
        TUNISIA: 'Tunisia',
        TURKEY: 'Turkey',
        TURKMENISTAN: 'Turkmenistan',
        TURKS_AND_CAICOS_ISLANDS: 'Turks and Caicos Islands',
        TUVALU: 'Tuvalu',
        US_VIRGIN_ISLANDS: 'US Virgin Islands',
        UGANDA: 'Uganda',
        UKRAINE: 'Ukraine',
        UNITED_ARAB_EMIRATES: 'United Arab Emirates',
        UNITED_KINGDOM: 'United Kingdom',
        UNITED_STATES: 'United States',
        UNITED_STATES_MINOR_OUTLYING_ISLANDS: 'United States Minor Outlying Islands',
        URUGUAY: 'Uruguay',
        UZBEKISTAN: 'Uzbekistan',
        VANUATU: 'Vanuatu',
        VATICAN_CITY: 'Vatican City',
        VENEZUELA: 'Venezuela',
        VIETNAM: 'Vietnam',
        WALLIS_AND_FUTUNA: 'Wallis and Futuna',
        WESTERN_SAHARA: 'Western Sahara',
        YEMEN: 'Yemen',
        YUGOSLAVIA: 'Yugoslavia',
        ZAMBIA: 'Zambia',
        ZIMBABWE: 'Zimbabwe'
    },
    nl: {
        AFGHANISTAN: 'Afghanistan',
        ALBANIA: 'Albanië',
        ALGERIA: 'Algerije',
        AMERICAN_SAMOA: 'Amerikaans Samoa',
        ANDORRA: 'Andorra',
        ANGOLA: 'Angola',
        ANGUILLA: 'Anguilla',
        ANTARCTICA: 'Antarctica',
        ANTIGUA_AND_BARBUDA: 'Antigua en Barbuda',
        ARGENTINA: 'Argentinië',
        ARMENIA: 'Armenië',
        ARUBA: 'Aruba',
        AUSTRALIA: 'Australië',
        AUSTRIA: 'Oostenrijk',
        AZERBAIJAN: 'Azerbeidzjan',
        BAHRAIN: 'Bahrein',
        BANGLADESH: 'Bangladesh',
        BARBADOS: 'Barbados',
        BELARUS: 'Wit-Rusland',
        BELGIUM: 'België',
        BELIZE: 'Belize',
        BENIN: 'Benin',
        BERMUDA: 'Bermuda',
        BHUTAN: 'Bhutan',
        BOLIVIA: 'Bolivia',
        BOSNIA_AND_HERZEGOVINA: 'Bosnië-Herzegovina',
        BOTSWANA: 'Botswana',
        BOUVET_ISLAND: 'Bouvet-eiland',
        BRAZIL: 'Brazilië',
        BRITISH_INDIAN_OCEAN_TERRITORY: 'Brits-Indisch oceaan gebied',
        BRITISH_VIRGIN_ISLANDS: 'Britse Maagdeneilanden',
        BRUNEI: 'Brunei',
        BULGARIA: 'Bulgarije',
        BURKINA_FASO: 'Burkina Faso',
        BURUNDI: 'Burundi',
        COTE_D_IVOIRE: 'Ivoorkust',
        CAMBODIA: 'Cambodja',
        CAMEROON: 'Kameroen',
        CANADA: 'Canada',
        CAPE_VERDE: 'Kaapverdië',
        CAYMAN_ISLANDS: 'Kaaiman Eilanden',
        CENTRAL_AFRICAN_REPUBLIC: 'Centraal Afrikaanse Republiek',
        CHAD: 'Tsjaad',
        CHILE: 'Chili',
        CHINA: 'China',
        CHRISTMAS_ISLAND: 'Kersteiland',
        COCOS_KEELING_ISLANDS: 'Cocos (Keeling) eilanden',
        COLOMBIA: 'Colombia',
        COMOROS: 'Comoren',
        CONGO: 'Congo',
        COOK_ISLANDS: 'Cookeilanden',
        COSTA_RICA: 'Costa Rica',
        CROATIA: 'Kroatië',
        CUBA: 'Cuba',
        CYPRUS: 'Cyprus',
        CZECH_REPUBLIC: 'Tsjechische Republiek',
        DEMOCRATIC_REPUBLIC_OF_THE_CONGO: 'Democratische Republiek Congo',
        DENMARK: 'Denemarken',
        DJIBOUTI: 'Djibouti',
        DOMINICA: 'Dominica',
        DOMINICAN_REPUBLIC: 'Dominicaanse Republiek',
        EAST_TIMOR: 'Oost Timor',
        ECUADOR: 'Ecuador',
        EGYPT: 'Egypte',
        EL_SALVADOR: 'El Salvador',
        EQUATORIAL_GUINEA: 'Equatoriaal-Guinea',
        ERITREA: 'Eritrea',
        ESTONIA: 'Estland',
        ETHIOPIA: 'Ethiopië',
        FAEROE_ISLANDS: 'Faeröer',
        FALKLAND_ISLANDS: 'Falkland Eilanden',
        FIJI: 'Fiji',
        FINLAND: 'Finland',
        FORMER_YUGOSLAV_REPUBLIC_OF_MACEDONIA: 'Voormalige Joegoslavische Republiek Macedonië',
        FRANCE: 'Frankrijk',
        FRENCH_GUIANA: 'Frans-Guyana',
        FRENCH_POLYNESIA: 'Frans-Polynesië',
        FRENCH_SOUTHERN_TERRITORIES: 'Franse zuidelijke gebieden',
        GABON: 'Gabon',
        GEORGIA: 'Georgië',
        GERMANY: 'Duitsland',
        GHANA: 'Ghana',
        GIBRALTAR: 'Gibraltar',
        GREECE: 'Griekenland',
        GREENLAND: 'Groenland',
        GRENADA: 'Grenada',
        GUADELOUPE: 'Guadeloupe',
        GUAM: 'Guam',
        GUATEMALA: 'Guatemala',
        GUINEA: 'Guinea',
        GUINEA_BISSAU: 'Guinee-Bissau',
        GUYANA: 'Guyana',
        HAITI: 'Haïti',
        HEARD_ISLAND_AND_MCDONALD_ISLANDS: 'Heard en McDonaldeilanden',
        HONDURAS: 'Honduras',
        HONG_KONG: 'Hong Kong',
        HUNGARY: 'Hongarije',
        ICELAND: 'IJsland',
        INDIA: 'India',
        INDONESIA: 'Indonesië',
        IRAN: 'Iran',
        IRAQ: 'Irak',
        IRELAND: 'Ierland',
        ISRAEL: 'Israël',
        ITALY: 'Italië',
        JAMAICA: 'Jamaica',
        JAPAN: 'Japan',
        JORDAN: 'Jordanië',
        KAZAKHSTAN: 'Kazachstan',
        KENYA: 'Kenia',
        KIRIBATI: 'Kiribati',
        KUWAIT: 'Koeweit',
        KYRGYZSTAN: 'Kirgizië',
        LAOS: 'Laos',
        LATVIA: 'Letland',
        LEBANON: 'Libanon',
        LESOTHO: 'Lesotho',
        LIBERIA: 'Liberia',
        LIBYA: 'Libië',
        LIECHTENSTEIN: 'Liechtenstein',
        LITHUANIA: 'Litouwen',
        LUXEMBOURG: 'Luxemburg',
        MACAU: 'Macau',
        MADAGASCAR: 'Madagascar',
        MALAWI: 'Malawi',
        MALAYSIA: 'Maleisië',
        MALDIVES: 'Maldiven',
        MALI: 'Mali',
        MALTA: 'Malta',
        MARSHALL_ISLANDS: 'Marshall eilanden',
        MARTINIQUE: 'Martinique',
        MAURITANIA: 'Mauritanië',
        MAURITIUS: 'Mauritius',
        MAYOTTE: 'Mayotte',
        MEXICO: 'Mexico',
        MICRONESIA: 'Micronesië',
        MOLDOVA: 'Moldavië',
        MONACO: 'Monaco',
        MONGOLIA: 'Mongolië',
        MONTSERRAT: 'Montserrat',
        MOROCCO: 'Marokko',
        MOZAMBIQUE: 'Mozambique',
        MYANMAR: 'Myanmar',
        NAMIBIA: 'Namibië',
        NAURU: 'Nauru',
        NEPAL: 'Nepal',
        NETHERLANDS: 'Nederland',
        NETHERLANDS_ANTILLES: 'Nederlandse Antillen',
        NEW_CALEDONIA: 'Nieuw-Caledonië',
        NEW_ZEALAND: 'Nieuw-Zeeland',
        NICARAGUA: 'Nicaragua',
        NIGER: 'Niger',
        NIGERIA: 'Nigeria',
        NIUE: 'Niue',
        NORFOLK_ISLAND: 'Norfolkeiland',
        NORTH_KOREA: 'Noord Korea',
        NORTHERN_MARIANAS: 'Noordelijke Marianen',
        NORWAY: 'Noorwegen',
        OMAN: 'Oman',
        PAKISTAN: 'Pakistan',
        PALAU: 'Palau',
        PANAMA: 'Panama',
        PAPUA_NEW_GUINEA: 'Papoea-Nieuw-Guinea',
        PARAGUAY: 'Paraguay',
        PERU: 'Peru',
        PHILIPPINES: 'Filippijnen',
        PITCAIRN_ISLANDS: 'Pitcairneilanden',
        POLAND: 'Polen',
        PORTUGAL: 'Portugal',
        PUERTO_RICO: 'Puerto Rico',
        QATAR: 'Qatar',
        REUNION: 'Bijeenkomst',
        ROMANIA: 'Roemenië',
        RUSSIA: 'Rusland',
        RWANDA: 'Rwanda',
        SAO_TOME_AND_PRÍNCIPE: 'São Tomé en Principe',
        SAINT_HELENA: 'Sint-Helena',
        SAINT_KITTS_AND_NEVIS: 'Saint Kitts en Nevis',
        SAINT_LUCIA: 'Saint Lucia',
        SAINT_PIERRE_AND_MIQUELON: 'Saint Pierre en Miquelon',
        SAINT_VINCENT_AND_THE_GRENADINES: 'Saint Vincent en de Grenadines',
        SAMOA: 'Samoa',
        SAN_MARINO: 'San Marino',
        SAUDI_ARABIA: 'Saoedi-Arabië',
        SENEGAL: 'Senegal',
        SEYCHELLES: 'Seychellen',
        SIERRA_LEONE: 'Sierra Leone',
        SINGAPORE: 'Singapore',
        SLOVAKIA: 'Slowakije',
        SLOVENIA: 'Slovenië',
        SOLOMON_ISLANDS: 'Solomon eilanden',
        SOMALIA: 'Somalië',
        SOUTH_AFRICA: 'Zuid-Afrika',
        SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS: 'Zuid-Georgië en de Zuid-Sandwicheilanden',
        SOUTH_KOREA: 'Zuid-Korea',
        SPAIN: 'Spanje',
        SRI_LANKA: 'Sri Lanka',
        SUDAN: 'Soedan',
        SURINAME: 'Suriname',
        SVALBARD_AND_JAN_MAYEN: 'Svalbard en Jan Mayen',
        SWAZILAND: 'Swaziland',
        SWEDEN: 'Zweden',
        SWITZERLAND: 'Zwitserland',
        SYRIA: 'Syrië',
        TAIWAN: 'Taiwan',
        TAJIKISTAN: 'Tadzjikistan',
        TANZANIA: 'Tanzania',
        THAILAND: 'Thailand',
        THE_BAHAMAS: 'De Bahamas',
        THE_GAMBIA: 'Gambia',
        TOGO: 'Gaan',
        TOKELAU: 'Tokelau',
        TONGA: 'Tonga',
        TRINIDAD_AND_TOBAGO: 'Trinidad en Tobago',
        TUNISIA: 'Tunesië',
        TURKEY: 'Kalkoen',
        TURKMENISTAN: 'Turkmenistan',
        TURKS_AND_CAICOS_ISLANDS: 'Turks- en Caicoseilanden',
        TUVALU: 'Tuvalu',
        US_VIRGIN_ISLANDS: 'Amerikaanse Maagdeneilanden',
        UGANDA: 'Oeganda',
        UKRAINE: 'Oekraïne',
        UNITED_ARAB_EMIRATES: 'Verenigde Arabische Emiraten',
        UNITED_KINGDOM: 'Verenigd Koningkrijk',
        UNITED_STATES: 'Verenigde Staten',
        UNITED_STATES_MINOR_OUTLYING_ISLANDS: 'Kleine afgelegen eilanden van de Verenigde Staten',
        URUGUAY: 'Uruguay',
        UZBEKISTAN: 'Oezbekistan',
        VANUATU: 'Vanuatu',
        VATICAN_CITY: 'Vaticaanstad',
        VENEZUELA: 'Venezuela',
        VIETNAM: 'Vietnam',
        WALLIS_AND_FUTUNA: 'Wallis en Futuna',
        WESTERN_SAHARA: 'Westelijke Sahara',
        YEMEN: 'Jemen',
        YUGOSLAVIA: 'Joegoslavië',
        ZAMBIA: 'Zambia',
        ZIMBABWE: 'Zimbabwe'
    }
};
